name: Control Push
on: push

jobs:
  qa:
    name: Check tests & lint
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Install the right Python version
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      # 3) Install pytest and flake8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8

      # 4) Run your tests
      - name: Run pytest
        run: pytest

      # 5) Run flake8 linter
      - name: Run flake8
        run: |
          # lint only your source + test files:
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics